# typed: false
# frozen_string_literal: true

# Homebrew formula for mosskeys-witness.
#
# The install / package name and the command it installs are both
# `mosskeys-witness`. This formula installs the prebuilt, signed binary attached
# to the GitHub Release (not a from-source build), so it shares the exact
# artifact that ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign
# signature, and SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-witness.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo
# (moss-piglet/homebrew-mosskeys-witness). Do not hand-edit checksums here.
class MosskeysWitness < Formula
  desc "Post-quantum-native C2SP tlog-witness (Ed25519 0x04 + ML-DSA-44 0x06)"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.3.0/mosskeys-witness-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "0c569056f2825d040c36ba3f1edbc2e530e2d18dd12a9f38e9cbceca793ec438"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.3.0/mosskeys-witness-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "7e8a9c27a83d9b6260ff2819bfbd4f1b52f36ece3605b83e215789e4297ce946"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.3.0/mosskeys-witness-0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2a16e109616abb026a7e5599d9ab334d5110b8e1d689df67d63579a679ee6c77"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.3.0/mosskeys-witness-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "78525af69adb9dcdf33d2e34e00ef5c47caefde7be199c38bb6e35e6b067ab3c"
    end
  end

  def install
    bin.install "mosskeys-witness"
  end

  test do
    assert_match "mosskeys-witness #{version}", shell_output("#{bin}/mosskeys-witness --version")
  end
end
