# typed: false
# frozen_string_literal: true

# Homebrew formula for mosskeys-witness.
#
# The install / package name and the command it installs are both
# `mosskeys-witness`. This formula installs the prebuilt, signed binary attached
# to the GitHub Release (not a from-source build), so it shares the exact
# artifact that ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign
# signature, and SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-witness.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo
# (moss-piglet/homebrew-mosskeys-witness). Do not hand-edit checksums here.
class MosskeysWitness < Formula
  desc "Post-quantum-native C2SP tlog-witness (Ed25519 0x04 + ML-DSA-44 0x06)"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.4.1/mosskeys-witness-0.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "c00e1c69594fbb87fda40cd8db3c00b085b9d5207cdf6f95c142f6a27fd80d7b"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.4.1/mosskeys-witness-0.4.1-x86_64-apple-darwin.tar.gz"
      sha256 "a966ed98db21e2eebb5555439ef7516d68ed5d06e06d88b84a912107a39d0c95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.4.1/mosskeys-witness-0.4.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "aedbc632b78defdf5c7e7643d70f06bdefb666cdbae1516a7b1288f9e854338b"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.4.1/mosskeys-witness-0.4.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d078a4393b433fe2d2604df646e5fa3ea7b342be2a297bfc88421b685d75a57a"
    end
  end

  def install
    bin.install "mosskeys-witness"
  end

  test do
    assert_match "mosskeys-witness #{version}", shell_output("#{bin}/mosskeys-witness --version")
  end
end
