# typed: false
# frozen_string_literal: true

# Homebrew formula for mosskeys-witness.
#
# The install / package name and the command it installs are both
# `mosskeys-witness`. This formula installs the prebuilt, signed binary attached
# to the GitHub Release (not a from-source build), so it shares the exact
# artifact that ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign
# signature, and SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-witness.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo
# (moss-piglet/homebrew-mosskeys-witness). Do not hand-edit checksums here.
class MosskeysWitness < Formula
  desc "Post-quantum-native C2SP tlog-witness (Ed25519 0x04 + ML-DSA-44 0x06)"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.2.0/mosskeys-witness-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "863875b345007603c412fde4777b4031dd3f7b8265af0ac2a4215e086251f003"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.2.0/mosskeys-witness-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "8208f3b9c2a3a12f9c22fcacfa9ab6c65e4c262d13fd15f3ca10cf67ae1c4f3c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.2.0/mosskeys-witness-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "383213929de63a68a18fa0d2fb7baadd01385d9ecd81e19e67ae4f72e4f835db"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.2.0/mosskeys-witness-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c818e53cb7cccda9d83bea8a4335919f040412f2d8184a800802a0d3c178114d"
    end
  end

  def install
    bin.install "mosskeys-witness"
  end

  test do
    assert_match "mosskeys-witness #{version}", shell_output("#{bin}/mosskeys-witness --version")
  end
end
